### ISSUE TITLE
brie seems to be incompatible with python3

### ISSUE THREAD

**Issue by RuyBlast** [huangyh09/brie#12]
Hello Yuanhua,

I built brie from source using python3 and I ended up with the error
TypeError: object of type 'map' has no len()
trying to run the brie-event command line. I built again brie with python2 and all went fine. Are you sure brie is compatible with python3 ? If not maybe you should write it on the readme and the website. (or fix it but it may be complicated)

Also, there is a typo in the brie website at https://brie-rna.sourceforge.io/manual.html
the command line example
brie-event-filter -a AS_events/SE.gff3 -anno_ref gencode.vM12.annotation.gtf -r GRCm38.p5.genome.fa
is false and does not run, it should be replaced by:
brie-event-filter -a AS_events/SE.gff3 --anno_ref=gencode.vM12.annotation.gtf -r GRCm38.p5.genome.fa

Best,
Milan

**Comment by huangyh09** [comment]
Hi Milan,

Many thanks for reporting this. You are right that the `brie-event` are not compatible with Python3 well. This is because the codes for generating splicing events are borrowed from Yaden's repo: https://github.com/yarden/rnaseqlib, and it is not easy to fully adapte these codes from Python2 to Python3.

I will add comments in the readme file and the manual, before correcting it.

Thanks
Yuanhua
