### ISSUE TITLE
How to generate feature files using Ensembl annotation file?

### ISSUE THREAD

**Issue by gangcai** [huangyh09/brie#18]
Hi Yuanhua,
       Is it possible to use Ensembl annotation file to generate the factor file? I had tried briekit-factor, however it seems that the chromosome names are not compatible with the phastCons annotation from UCSC.

Thanks,
Gangcai

**Comment by huangyh09** [comment]
Hi Gangcai,
It should be fine to use ensemble annotation, but you may need to adapt the chromsome names to the phastCons file. BTW, which species are you using?

Cheers
Yuanhua

**Comment by gangcai** [comment]
Hi Yuanhua,
        Thanks for your reply. I am working on mouse genome.  Currently, the mapping of the reads was done on Ensembl genome, so in order to make it compatible with UCSC phastCons files, I need to change all the chromosome names in the bam files (some chromosome fragment names could not find matched UCSC chr names)

Best,
Gangcai

**Comment by huangyh09** [comment]
Hi Gangcai,
I see your point. You don't need to change the bam file. You can change the chromsome name in the GFF file when fetching the features from phastCons, and the feature file only contains transcript id rather than chromesome names. Then you can use the orignal GFF file for quantification with BRIE.
Note, you need to generate the splicing event GFF from the full gene annotation GFF first, anyway.
Cheers
Yuanhua
