### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by Byronxy** [huangyh09/brie#34]
Hi, I set up the environment as you described. And I tested with the example data and got the error.
![image](https://user-images.githubusercontent.com/28949856/90998457-ba633200-e5f6-11ea-8964-a92657dcb1a8.png)

**Comment by huangyh09** [comment]
Hi, thanks for the testing. BRIE2 takes a list of sam files in the `-S` option instead of each sam file. 

Please follow the quick start example: https://brie.readthedocs.io/en/latest/quick_start.html or the the new demo file: https://github.com/huangyh09/brie/blob/master/examples/brie2_demo.sh

Also, please upgrade to v2.0.2 from github
```
pip install -U git+https://github.com/huangyh09/brie
```
Let us know if it resolves your issue.

Yuanhua

**Comment by Byronxy** [comment]
Hi, I successfully run the brie_count. However, I got an error when running brie-quant
![image](https://user-images.githubusercontent.com/28949856/91005267-0919c780-e609-11ea-9eb3-974ad647b474.png)

**Comment by huangyh09** [comment]
Good. It looks you only have three cells, and all genes are filtered out, as by default `--minCell=30`, namely only genes having >= 30 cells with unique reads are kept. You could set `--minCell=0`.

**Comment by Byronxy** [comment]
Thanks a lot! I got the result! 
![image](https://user-images.githubusercontent.com/28949856/91006559-46338900-e60c-11ea-9fa8-1adfc9d5ab92.png)
