### ISSUE TITLE
ELBO_gain and effect size

### ISSUE THREAD

**Issue by seongguheo** [huangyh09/brie#59]
Dear Authors,

Thank you for your wonderful work.
I am struggling to understand the practical meaning of ELBO_gain and effect size of the Volcano plot between ELBO_gain and effect size on logit(PSI) for detecting differential splicing between EAE and control cells by BRIE2.
If you could give some explanation of those meaning in a simple/easy way, it would be great.

Many thanks.
Luke

**Comment by huangyh09** [comment]
Hi Luke,

Thanks for the questions. Let me try explaining in plain text:
- ELBO_gain is somewhat like the difference of log-likelihood between two models, except with variational inference it is expected log-likelihood, instead of point estimate log-likelihood.
- effect size is the weight in the regression model. As the linear relationship applies for logit transformed PSI value, you can take it as the effect size on logit(PSI).

Hope it may help.
Yuanhua
