### ISSUE TITLE
Is BRIE2 appliable in 10x Genomics scRNA data

### ISSUE THREAD

**Issue by cynthier** [huangyh09/brie#63]
"Naturally, protocols such as CEL-seq or STRT-seq that bias reads towards the ends of the transcript cannot provide information about exon-skipping events that may be very far from the ends of a transcript."

I saw this in BRIE article, and I am not sure whether BRIE2 can be used in 10x Genomics scRNA data which also is PolyA-tailed mRNA data.

**Comment by huangyh09** [comment]
Hi, thanks for the question.

From version 2.2.2, the answer is yes (but it also depends on the splicing events you are interested in), see the updates in the [manual](https://brie.readthedocs.io/en/latest/index.html#top-news).

This new setting is generic for any two-isoform annotations, no matter where the alternative exons are. However, since the sequencing is biased, you may see very limited coverage of exon-skipping, while if you are interested in the exon changes near the poly-A site, the chance will be larger. You may take [Fig. 4D](https://academic.oup.com/brain/article/147/2/554/7457295) in this work as an example of how BRIE2 can work with 10x Genomics data.

Yuanhua

**Comment by huangyh09** [comment]
BTW, if you are particularly interested in the alternative poly-A site, we are working on a new tool specifically for that and may be available in ~2 months. Stay tuned.

**Comment by cynthier** [comment]
Thank you so much!

**Comment by cynthier** [comment]
Thank you so much! @huangyh09

**Comment by cynthier** [comment]
> BTW, if you are particularly interested in the alternative poly-A site, we are working on a new tool specifically for that and may be available in ~2 months. Stay tuned.

Look forward to your great work!
