### ISSUE TITLE
Freeze during h5ad converting

### ISSUE THREAD

**Issue by shiquan** [huangyh09/brie#65]
Hi,

I am processing data generated with Smartseq2. For some reason, I merged all cells into one sorted and indexed BAM file, with each cell distinguished by the RG tag. I used the following command to count the events, but the process always freezes at the last step. Below is the snapshot and the command I used:

`brie-count -b cells.csv --cellTAG=RG --UMItag=RG -p 40 -o ./ -s merged.bam -a SE.filtered.gff3.gz `
 
![image](https://github.com/user-attachments/assets/60873a8d-49fb-420d-b6c4-2eaee25cfd65)

Thanks and looking forward to hearing from you soon.

BR, Quan

**Comment by huangyh09** [comment]
Hi Quan,
Thanks for sharing the issue. I'm unsure how to fix it quickly, but using UMItag as RG may cause another big problem. Since all reads in one cell have the same RG, it will treat them as one UMI if you use it UMItag. I guess you may have to split them into individual bam files, then input them into the brie-count.

Yuanhua

**Comment by shiquan** [comment]
Dear Yuanhua,

Thank you for your quick reply. After setting up different threads, I believe the issue may be caused by multithreading. The process freezes when I set -p to 40, but it works fine with other configurations. Additionally, I've noticed an issue with the UMItag, and I am currently working on splitting the cells. I appreciate your advice.

Quan
