### ISSUE TITLE
Brie isoform expression quantification error  

### ISSUE THREAD

**Issue by s6juncheng** [huangyh09/brie#8]
Hi Yuanhua,

thanks for providing the tool for splicing analysis. I got an error when running brie for isoform expression.

brie -a AS_events/SE.gold.gtf -s sample.bam -f AS_events/human_features_v19.csv.gz -o AS_events/ -p 50                                     
[Brie] loading annotation file... Done.
[Brie] loading reads for 12504 genes with 50 cores...
[Brie] [====================] 100.0% done in 58.5 sec.
[Brie] running Brie for 25008 isoforms on 12504 genes with 50 cores...
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/3-4.1.1/envs/python27/bin/brie", line 11, in <module>
    load_entry_point('brie==0.1.3', 'console_scripts', 'brie')()
  File "build/bdist.linux-x86_64/egg/brie/brie.py", line 268, in main
  File "build/bdist.linux-x86_64/egg/brie/models/model_brie.py", line 300, in brie_MH_Heuristic
  File "build/bdist.linux-x86_64/egg/brie/models/model_brie.py", line 159, in Iso_read_check
IndexError: index 0 is out of bounds for axis 0 with size 0

It might because my bam file uses ensembl chromosome names (1, 2, 3...) while the annotation SE.gold.gtf is from gencode followed you instructions.

I tried to generate brie-factor with ensembl annotation, it gave warnings like "No PhastCons data for ENSG...in. Treated as Zero". As PhastCons file is from UCSC, I assume the problem is again because of chromosome names. 

Besides, the same error of brie for isoform expression persist if I use SE.gold.gtf generated from ensembl and human_features generated from gencode (as I cann't generate human_features from ensembl, see above).

Is there a way to get around of this?

Best wishes,
Jun

**Comment by huangyh09** [comment]
Hi Jun,

Glad to hear from you and you are using BRIE.

Normally, BRIE can handle the the bam file that aligned to Ensembl reference, see [here](https://github.com/huangyh09/brie/blob/master/brie/utils/sam_utils.py#L56):

I assume that you aligned your fastq file to Ensembl genome. Could you point out which aligner and which reference file you used? So I could have a try with some example data.

I think you are right that `brie-factor` doesn't support the different chromosome id in annotation file and PhastCons file in bigWig format. See [here](https://github.com/huangyh09/brie/blob/master/brie/utils/fasta_utils.py#L128).

I think the simplest thing you could do is to modify the chromosome id in the annotation file by simply removing _chr_, so that you could run `brie` with your bam file. During the meantime, I will try to upgrade the program to support the differences in chromosome ids.

Cheers,
Yuanhua

**Comment by s6juncheng** [comment]
Hi Yuanhua, 

the problem solved when I install with pip in python3. Before the installation was done with python2.7 from source that cloned from your master branch. Not sure whether it was because of python2, but glad that my problem solved. Thanks!

Cheers,
Jun

**Comment by huangyh09** [comment]
Hi Jun,

Glad that the issue has been solved. In my environment, both Python 2.7 and 3.3 works well, with BRIE v0.1.3. Earlier version may cause such problems.

Cheers,
Yuanhua
